# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Javier/anaconda3/Library/include
    lib directory: C:/Users/Javier/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Javier/anaconda3/Library/include
    lib directory: C:/Users/Javier/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
    name: cython


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
arr = np.zeros(10, dtype="int32")
print(arr)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
#Each element size
a = arr.itemsize
print("Each element size:", a, "bytes")

#Data size
b = arr.size * a
print("Data size: ", b, "bytes")

#Total size: Metadata + data
c = arr.__sizeof__()
print("Total size: ",c,"bytes")

Each element size: 4 bytes
Data size:  40 bytes
Total size:  152 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
!python -c "import numpy; print(numpy.info(numpy.add))"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
arr = np.zeros(10, dtype="int32")
arr[4] = 1
print(arr)


[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
arr = arr[::-1]
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
arr = np.arange(0, 9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)[0]
print(indices)

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
rng = np.random.default_rng(1)

arr = rng.integers(0, 10, (3, 3))
print(arr)

[[4 5 7]
 [9 0 1]
 [8 9 2]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
arr = rng.integers(0, 200, (10, 10))
print(arr)
print("Maximum: ", arr.max())
print("Minimum: ", arr.min())

[[ 62 173  84  54 165  51  81 128 109  17]
 [  5 173 150 167 107 163  65  90 157  24]
 [ 60  24  90 195  26  76  80 180  40 100]
 [ 52   3 150  12  56  99  97  23 196 149]
 [192  18 144  58 108 184  55 145  32  64]
 [193  84 103  58  23  84 124  91 155  72]
 [122 154 183  85   7 143 105 174  91  73]
 [ 12  91 128 154 170  42 118 160  52  68]
 [167 116 101 134 102 196 150  10  29 109]
 [163  13 136 151 157 174  38 111 160  71]]
Maximum:  196
Minimum:  3


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
arr = rng.uniform(0, 3, 30)
print(arr.mean())

1.7120433751313398


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
n = 5
arr = np.ones((n, n), dtype="int32")
arr[1:-1, 1:-1] = 0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
dims = np.array(arr.shape) + 2
arr2 = np.zeros(dims)

print(arr[(1, -1), (1, -1)])



[0 1]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
'''
1. np.nan: Operations with np.nan makes everything nan
2. true: Same thing equal same thing
3. false: There's no order of nan and inf
4. np.nan: Operations with np.nan makes everything nan
5. true: Is an object that in fact belongs to a set
6. false: Precision of stored number makes both things unequal
'''

"\n1. np.nan: Operations with np.nan makes everything nan\n2. true: Same thing equal same thing\n3. false: There's no order of nan and inf\n4. np.nan: Operations with np.nan makes everything nan\n5. true: Is an object that in fact belongs to a set\n6. false: Precision of stored number makes both things unequal\n"

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
arr = np.diag(np.array([1, 2, 3, 4]), k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
arr = np.zeros((8, 8), dtype="int32")
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
index = 100-1

x = index//(7*8)
index -= 7*8*x

y = index//8
index -= 8*y

z = index
index -= z

print(x, y, z)


#Test
arr = np.zeros(6*7*8, dtype="int32")
arr[99] = 1
arr = arr.reshape(6, 7, 8)
print(arr)

1 5 3
[[[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 1 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]]


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
#np.info(np.tile)

arr = np.tile(np.array([0, 1]), 4)
arr = np.vstack((arr, 1- arr))
arr = np.tile(arr, (4, 1))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
arr = rng.uniform(0, 30, (5,5))

print(arr)
print()

#Simple min-max
maxim = arr.max()
minim = arr.min()
arr2 = (arr - minim)/(maxim - minim)
print("Min-Max")
print(arr2)
print()

#Per-Column standarization
mu = arr.mean(axis=0)
sigma = arr.std(axis=0, ddof=1)

arr2 = (arr-mu)/sigma

print("Standarization")
print(arr2)
print()



[[ 1.88153768 24.7646344   4.93521799 11.25440989  9.502145  ]
 [20.74011106  5.35715635 11.88768487  0.17473785  7.87484138]
 [12.63566443  3.1776371  18.99479838 11.4127281  21.75881814]
 [19.61598033 12.93680246 26.01961517 18.96405353 24.30823056]
 [10.25384172 16.31007869  5.88890655 29.8842357   7.29646393]]

Min-Max
[[0.05744964 0.82767796 0.16023428 0.37293367 0.31395371]
 [0.69221544 0.17443642 0.39424924 0.         0.25917986]
 [0.41942569 0.1010754  0.63346949 0.37826254 0.72650438]
 [0.65437802 0.42956177 0.8699197  0.63243464 0.81231574]
 [0.33925528 0.54310379 0.19233475 1.         0.2397121 ]]

Standarization
[[-1.4539822   1.40797776 -0.96141851 -0.28098338 -0.56650101]
 [ 1.00656179 -0.82168089 -0.18508754 -1.29057617 -0.76492505]
 [-0.05085369 -1.07207839  0.6085117  -0.26655724  0.92800722]
 [ 0.85989252  0.04911868  1.39292146  0.42152845  1.23886791]
 [-0.36161842  0.43666283 -0.85492711  1.41658833 -0.83544907]]



#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
A = rng.uniform(0, 5, (5, 3))
B = rng.uniform(0, 5, (3, 2))

print(A)
print()
print(B)
print()

C = np.dot(A, B)
print(C)

[[1.28433734 0.36595036 1.28901559]
 [3.81564266 3.48946785 0.64336606]
 [1.88119251 2.10460697 3.32492123]
 [2.27964482 2.93259163 4.19842302]
 [3.63236805 1.82503632 2.24198155]]

[[1.83849785 0.54867332]
 [1.01620772 1.41903244]
 [1.57066948 1.56523929]]

[[ 4.75775046  3.24159493]
 [11.57159043  8.05223127]
 [10.81963853  9.22296308]
 [13.76557924 11.98375965]
 [12.05412883  8.0920068 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
arr = rng.integers(0, 10, 20)
print(arr)
mask = (arr>=3) & (arr<=8)
arr[(arr<=8) & (arr>=3)] *= -1
print(arr)

[1 9 5 1 9 8 7 1 7 7 7 7 5 3 9 9 6 3 5 5]
[ 1  9 -5  1  9 -8 -7  1 -7 -7 -7 -7 -5 -3  9  9 -6 -3 -5 -5]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
'''
9: In the first line, the sum function is the built-in sum function of python, will just sum from 0 to 4 and add -1
10: The third line sum function is np.sum, the -1 means to sum the last axis (In this case there is only one), so just sum up from 0 to 4
'''

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [27]:
arr1 = rng.integers(0, 10, 10)
arr2 = rng.integers(0, 10, 10)

print(arr1)
print(arr2)
print(np.intersect1d(arr1, arr2))



[0 0 4 5 2 2 1 9 5 2]
[7 9 2 8 7 7 5 9 1 0]
[0 1 2 5 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [28]:
A = rng.uniform(0, 10, 10)
B = rng.uniform(0, 10, 10)

A += B
A *= np.divide(np.multiply(-1.0, np.subtract(A, B, out=A), out=A), 2.0)

print(A)

[ 8.06558282  4.35816329 35.87031199  0.77451872 26.90774823  1.7639067
  7.70248971  2.68887768 35.38322678  7.6079078 ]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [32]:
arr = np.arange(0, 5)
arr = np.tile(arr, (5, 1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [43]:
arr = rng.integers(0, 100, 10)
print(arr)

[96 71 63 42 36 94 76 39  2 12]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [44]:
arr = rng.uniform(np.power(2.0, -1075), 1, 10)
print(arr)

[0.37185457 0.47707401 0.12762069 0.22250687 0.56205159 0.38776912
 0.79165621 0.60513659 0.86126668 0.73236084]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [29]:
arr = rng.uniform(0, 1, 10)
arr.sort()
print(arr)

[0.01672282 0.28546523 0.35978693 0.38098154 0.38149293 0.49357156
 0.50380295 0.64151359 0.74821796 0.97159841]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
arr = rng.uniform(0, 10, (10, 2))
X = arr[:,0]
Y = arr[:,1]

r = np.power(X)

[[6.01823448 2.87615602]
 [7.82760468 2.51267578]
 [0.75211112 9.62864578]
 [5.40011205 7.73894298]
 [5.29222808 6.1157973 ]
 [0.33892251 1.86793679]
 [6.74689395 5.70564598]
 [1.58555034 9.52029269]
 [1.54353633 5.1030325 ]
 [1.44002875 7.17371726]]
[6.01823448 7.82760468 0.75211112 5.40011205 5.29222808 0.33892251
 6.74689395 1.58555034 1.54353633 1.44002875]
[2.87615602 2.51267578 9.62864578 7.73894298 6.1157973  1.86793679
 5.70564598 9.52029269 5.1030325  7.17371726]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)